repos:
  - repo: local
    hooks:
      - id: rustfmt-nightly
        name: rustfmt-nightly
        entry: bash -c "cargo +nightly fmt --all -- --check"
        language: system
        files: \\.rs$
