# -------------------------------------------------------------------------------------
# NOTE FOR MAINTAINERS:
#
# This workflow is intentionally configured to use ONLY pre-built Skia binaries.
# Do NOT add installation steps for gn, ninja, depot_tools, or any Skia source build tools.
#
# Why?
# - Source building Skia is slow and unstable in CI (missing tools, corrupted binaries, git errors, etc.)
# - Pre-built Skia binaries (via FORCE_SKIA_BINARIES_DOWNLOAD=1 and related env vars) are fast and reliable.
# - This mirrors the local debug_plugin.bat script and eliminates all prior CI failures.
#
# To upgrade Skia, ONLY update SKIA_BINARIES_URL and SKIA_BINARIES_KEY to point at a new prebuilt release.
# If you need to build Skia from source, do so locally and contribute new binaries upstream.
#
# See commit bfe64569821613638ad91266a19215bbdc22d1b5 and the workflow run at
# https://github.com/fsecada01/bus_channel_strip/actions/runs/17618457424/job/50057771486
# for full rationale and history.
# -------------------------------------------------------------------------------------

name: Create VST3/CLAP Release

on:
  push:
    branches:
      - main
      - 'v[0-9]+*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            name: linux
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: windows
          - target: x86_64-apple-darwin
            os: macos-13
            name: macos-intel
          - target: aarch64-apple-darwin
            os: macos-14
            name: macos-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          clang \
          libasound2-dev \
          libfreetype6-dev \
          libfontconfig-dev \
          libglu1-mesa-dev \
          libegl1-mesa-dev \
          libx11-dev \
          libx11-xcb-dev \
          libxcb1-dev \
          libxcb-render0-dev \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxss-dev \
          pkg-config \
          build-essential


      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          # Configure Rust for MSVC target (matches local script)
          rustup target add x86_64-pc-windows-msvc

      - name: Set environment for pre-built Skia binaries
        shell: bash
        run: |
          # Force binary downloads using rust-skia's actual environment variables
          echo "FORCE_SKIA_BINARIES_DOWNLOAD=1" >> $GITHUB_ENV
          echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
          echo "CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true" >> $GITHUB_ENV
          
          # Optionally point rust-skia at your own prebuilt tarball and key using repository Variables (Actions -> Variables)
          # - SKIA_BINARIES_URL: Full URL to the prebuilt tarball (or leave unset to use rust-skia defaults)
          # - SKIA_BINARIES_KEY: Optional override for the binary key (platform/features selector)
          if [[ -n "${{ vars.SKIA_BINARIES_URL }}" ]]; then
            echo "SKIA_BINARIES_URL=${{ vars.SKIA_BINARIES_URL }}" >> $GITHUB_ENV
          fi
          if [[ -n "${{ vars.SKIA_BINARIES_KEY }}" ]]; then
            echo "SKIA_BINARIES_KEY=${{ vars.SKIA_BINARIES_KEY }}" >> $GITHUB_ENV
          fi

          # On Linux, avoid requiring EGL headers if a source build is triggered
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "SKIA_GN_ARGS=skia_use_egl=false" >> $GITHUB_ENV
          fi

          # Set platform-specific environment for ARM64 zlib issue only
          if [[ "${{ matrix.target }}" == "aarch64-apple-darwin" ]]; then
            echo "CFLAGS=-DZLIB_DISABLE_CHUNK_SIMD" >> $GITHUB_ENV
            echo "CXXFLAGS=-DZLIB_DISABLE_CHUNK_SIMD" >> $GITHUB_ENV
          fi
          # Do NOT set DOCS_RS in CI. That variable is meant for docs.rs
          # and forces skia-bindings into a special docs build path that
          # fails outside docs.rs with missing files.

      - name: Prepare Skia offline tarball (optional)
        if: ${{ vars.SKIA_BINARIES_URL != '' }}
        shell: bash
        run: |
          set -euo pipefail
          url="${{ vars.SKIA_BINARIES_URL }}"
          # If the provided URL is http(s), download it locally and point SKIA_BINARIES_URL to a file:// path
          if [[ "$url" =~ ^https?:// ]]; then
            out="$RUNNER_TEMP/skia-prebuilt.tar.gz"
            curl -fsSL "$url" -o "$out"
            echo "SKIA_BINARIES_URL=file://$out" >> "$GITHUB_ENV"
          fi
          # If SKIA_BINARIES_URL was already a file:// or absolute path, the previous step has exported it unchanged.

      - name: Build xtask
        run: |
          cargo +nightly build --package xtask

      - name: Build and bundle plugins (with GUI for all platforms)
        run: |
          cargo +nightly run --package xtask -- bundle bus_channel_strip --release --target ${{ matrix.target }} --features api5500,buttercomp2,transformer,gui

      - name: Create archive name
        id: archive
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            echo "name=Bus-Channel-Strip-${{ matrix.name }}.zip" >> $GITHUB_OUTPUT
          else
            echo "name=Bus-Channel-Strip-${{ matrix.name }}.tar.gz" >> $GITHUB_OUTPUT
          fi

      - name: Create archive
        shell: bash
        run: |
          cd target/bundled
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            zip -r Bus-Channel-Strip-${{ matrix.name }}.zip Bus-Channel-Strip.vst3 Bus-Channel-Strip.clap
          else
            tar -czf Bus-Channel-Strip-${{ matrix.name }}.tar.gz Bus-Channel-Strip.vst3 Bus-Channel-Strip.clap
          fi
          ls -la

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.archive.outputs.name }}
          path: target/bundled/${{ steps.archive.outputs.name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/v')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo "VERSION=$(grep -m 1 'version' Cargo.toml | cut -d '"' -f 2)" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: |
          echo "=== Downloaded artifacts ==="
          ls -la artifacts/
          find artifacts/ -type f

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: Bus Channel Strip v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' }}

      - name: Upload Linux release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/Bus-Channel-Strip-linux.tar.gz/Bus-Channel-Strip-linux.tar.gz
          asset_name: Bus-Channel-Strip-linux.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/Bus-Channel-Strip-windows.zip/Bus-Channel-Strip-windows.zip
          asset_name: Bus-Channel-Strip-windows.zip
          asset_content_type: application/zip

      - name: Upload macOS Intel release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/Bus-Channel-Strip-macos-intel.tar.gz/Bus-Channel-Strip-macos-intel.tar.gz
          asset_name: Bus-Channel-Strip-macos-intel.tar.gz
          asset_content_type: application/gzip

      - name: Upload macOS ARM64 release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/Bus-Channel-Strip-macos-arm64.tar.gz/Bus-Channel-Strip-macos-arm64.tar.gz
          asset_name: Bus-Channel-Strip-macos-arm64.tar.gz
          asset_content_type: application/gzip
